USE Wordle
GO

--Populate the tables that form the basis of the way the guesses interact with the word list

--Letters
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('a',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('b',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('c',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('d',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('e',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('f',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('g',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('h',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('i',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('j',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('k',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('l',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('m',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('n',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('o',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('p',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('q',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('r',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('s',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('t',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('u',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('v',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('w',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('x',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('y',0)
INSERT INTO dbo.Letters (Letter,LetterCount) VALUES ('z',0)

--All Words Letters
INSERT INTO dbo.WordsLetters (WordID,LetterIndex,LetterID)
SELECT AW.WordID, 1, L.LetterID
FROM dbo.Words AW
INNER JOIN dbo.Letters L ON (SUBSTRING(AW.Word,1,1)=L.Letter)

INSERT INTO dbo.WordsLetters (WordID,LetterIndex,LetterID)
SELECT AW.WordID, 2, L.LetterID
FROM dbo.Words AW
INNER JOIN dbo.Letters L ON (SUBSTRING(AW.Word,2,1)=L.Letter)

INSERT INTO dbo.WordsLetters (WordID,LetterIndex,LetterID)
SELECT AW.WordID, 3, L.LetterID
FROM dbo.Words AW
INNER JOIN dbo.Letters L ON (SUBSTRING(AW.Word,3,1)=L.Letter)

INSERT INTO dbo.WordsLetters (WordID,LetterIndex,LetterID)
SELECT AW.WordID, 4, L.LetterID
FROM dbo.Words AW
INNER JOIN dbo.Letters L ON (SUBSTRING(AW.Word,4,1)=L.Letter)

INSERT INTO dbo.WordsLetters (WordID,LetterIndex,LetterID)
SELECT AW.WordID, 5, L.LetterID
FROM dbo.Words AW
INNER JOIN dbo.Letters L ON (SUBSTRING(AW.Word,5,1)=L.Letter)

--LetterPositions
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (1,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (2,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (3,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (4,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (5,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (6,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (7,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (8,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (9,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (10,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (11,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (12,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (13,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (14,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (15,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (16,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (17,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (18,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (19,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (20,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (21,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (22,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (23,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (24,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (25,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (26,1,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (1,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (2,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (3,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (4,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (5,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (6,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (7,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (8,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (9,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (10,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (11,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (12,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (13,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (14,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (15,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (16,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (17,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (18,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (19,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (20,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (21,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (22,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (23,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (24,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (25,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (26,2,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (1,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (2,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (3,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (4,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (5,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (6,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (7,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (8,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (9,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (10,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (11,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (12,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (13,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (14,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (15,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (16,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (17,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (18,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (19,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (20,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (21,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (22,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (23,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (24,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (25,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (26,3,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (1,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (2,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (3,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (4,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (5,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (6,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (7,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (8,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (9,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (10,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (11,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (12,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (13,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (14,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (15,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (16,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (17,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (18,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (19,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (20,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (21,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (22,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (23,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (24,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (25,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (26,4,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (1,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (2,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (3,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (4,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (5,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (6,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (7,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (8,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (9,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (10,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (11,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (12,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (13,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (14,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (15,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (16,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (17,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (18,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (19,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (20,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (21,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (22,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (23,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (24,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (25,5,1)
INSERT INTO dbo.LetterPositions (LetterID,LetterIndex,LetterStatus) VALUES (26,5,1)

--Scoring Models
INSERT INTO dbo.ScoringModels (ScoringModel) VALUES ('Letter frequency')
INSERT INTO dbo.ScoringModels (ScoringModel) VALUES ('Letter frequency with position')
INSERT INTO dbo.ScoringModels (ScoringModel) VALUES ('Letter frequency with position (duplicates)')
INSERT INTO dbo.ScoringModels (ScoringModel) VALUES ('Letter frequency with position (duplicates root)')

--Models
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('All letter frequency',1)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('All letter frequency with position',2)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('All letter frequency with position (duplicates)',3)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('All letter frequency with position (duplicates root)',4)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('Adjust start letter frequency',1)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('Adjust start letter frequency with position',2)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('Adjust start letter frequency with position (duplicates)',3)
INSERT INTO dbo.Models (Model, ScoringModelID) VALUES ('Adjust start letter frequency with position (duplicates root)',4)


--Model intial guesses
--These are the three words with best rank that use 15 different letters
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (5, 1, (SELECT WordID FROM Words WHERE Word='tares'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (5, 2, (SELECT WordID FROM Words WHERE Word='doily'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (5, 3, (SELECT WordID FROM Words WHERE Word='punch'))

INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (6, 1, (SELECT WordID FROM Words WHERE Word='tares'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (6, 2, (SELECT WordID FROM Words WHERE Word='doily'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (6, 3, (SELECT WordID FROM Words WHERE Word='punch'))

INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (7, 1, (SELECT WordID FROM Words WHERE Word='tares'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (7, 2, (SELECT WordID FROM Words WHERE Word='doily'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (7, 3, (SELECT WordID FROM Words WHERE Word='punch'))

INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (8, 1, (SELECT WordID FROM Words WHERE Word='tares'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (8, 2, (SELECT WordID FROM Words WHERE Word='doily'))
INSERT INTO [dbo].[ModelInitialGuesses] (ModelID, GuessNumber, WordID) VALUES (8, 3, (SELECT WordID FROM Words WHERE Word='punch'))